### PR TITLE
CircleCI: Run some key flake8 tests

### PR DESCRIPTION
**Pull request by cclauss**
These tests find Python syntax errors and undefined names.

### CODE REVIEW

**Comment by my8100** [comment]
Do you know why CI is not triggered by your PR?
It worked on my PR #62.

**Comment by cclauss** [comment]
I will rebase...

**Comment by cclauss** [comment]
Rebasing did not change anything.  It is not clear to me why CircleCI did not run on this PR.

**Comment by my8100** [comment]
Could you send the PR in a new branch?

**Comment by cclauss** [comment]
> Add more commits by pushing to the patch-1 branch on cclauss/scrapydweb.

But I will try...

**Comment by cclauss** [comment]
Closing in favor of #64

**Pull request closed without merging**
