### PR TITLE
CircleCI: Run some key flake8 tests

### PR DESCRIPTION
**Pull request by cclauss**
These tests find Python syntax errors and undefined names.
(A second attempt at #63)

### CODE REVIEW

**Comment by cclauss** [comment]
Does not kick off a CircleCI build.  :-(

Check the setting at https://circleci.com/gh/my8100/scrapydweb/edit

**Comment by my8100** [comment]
> Does not kick off a CircleCI build. :-(
> 
> Check the setting at https://circleci.com/gh/my8100/scrapydweb/edit

I just found that "Build forked pull requests" is off by default.
Sorry for the inconvenience.

**Comment by my8100** [comment]
Could you push again?

**Comment by cclauss** [comment]
Yeah!!

**Comment by my8100** [comment]
You have to pull my previous commit https://github.com/my8100/scrapydweb/commit/1ea0ab3946a251a22a7c753510922955485eba8f first
in order to get all the tests to pass.

**Comment by my8100** [comment]
BTW, don't forget to rollback your change in *README.md*.

**Comment by cclauss** [comment]
I liked my change to README.md

**Comment by my8100** [comment]
Details on `--select=E9,F63,F7,F82`: https://github.com/deepmipt/DeepPavlov/pull/913#issue-294047319
```
flake8 . --count --exclude=./venv* --select=E9,F63,F7,F82 --show-source --statistics
```
On the flake8 test selection, this PR does not focus on "style violations" (the majority of flake8 error codes that [python/black](https://github.com/python/black) can autocorrect). Instead these tests are focus on runtime safety and correctness:

- E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST). Often these issues are a sign of unused code or code that has not been ported to Python 3. These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
- F63 tests are usually about the confusion between identity and equality in Python. Use ==/!= to compare str, bytes, and int literals is the classic case. These are areas where a == b is True but a is b is False (or vice versa).
- F7 tests logic errors and syntax errors in type hints
- F82 tests are almost always undefined names which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3. These also would be compile-time errors in a compiled language but in Python a NameError is raised which will halt/crash the script on the user.

**Pull request merged**
